version: "3.2"
services:
  contact-regex:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8082:8081"
    links:
      - mysqldb
  mysqldb:
    image: mysql:8
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: contact_regex
      MYSQL_PASSWORD: 1979
      MYSQL_ROOT_PASSWORD: 1979